apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: skjemabygging-proxy-alerts
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
spec:
  receivers:
    slack:
      channel: '#skjemautfylling-feil-prod'
      prependText: '<!here> | ' # this text will be prepended to the Slack alert title
  alerts:
    - alert: skjemabygging-proxy nede
      expr: kube_deployment_status_replicas_available{deployment="skjemabygging-proxy"} == 0
      for: 1m
      description: "{{ $labels.deployment }} er nede"
      action: "`kubectl get pods --namespace {{ $labels.namespace }}`"
