apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{name}}
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
spec:
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
      tenant: {{azure.application.tenant}}
  accessPolicy:
    inbound:
      rules:
        {{#each accessPolicy.inbound.rules}}
           - application: {{this.application}}
             namespace: {{this.namespace}}
             cluster: {{this.cluster}}
        {{/each}}
    outbound:
      external:
        {{#each accessPolicy.outbound.external}}
          - host: {{this.host}}
        {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  liveness:
    path: /internal/health/liveness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: internal/prometheus
  env:
  {{#each env}}
      - name: {{this.name}}
        value: {{this.value}}
  {{/each}}
