ingresses:
  - https://skjemabygging-proxy.intern.nav.no
  - https://skjemabygging-proxy.prod-fss-pub.nais.io
env:
  - name: NORG2_BASE_URL
    value: https://norg2.nais.adeo.no
  - name: OPPDATERENHETSINFO_BASE_URL
    value: http://oppdaterenhetsinfo
  - name: FOERSTESIDEGENERATOR_BASE_URL
    value: https://foerstesidegenerator.intern.nav.no
  - name: STS_TOKEN_URL
    value: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
  - name: SERVICEUSER_USERNAME
    value: srvsoknadsveiviser
azure:
  application:
    tenant: nav.no
accessPolicy:
  inbound:
    rules:
      - application: skjemautfylling
        namespace: skjemadigitalisering
        cluster: prod-gcp
      - application: soknadsveiviser
        namespace: skjemadigitalisering
        cluster: prod-gcp
      - application: skjemabygging-formio
        namespace: skjemadigitalisering
        cluster: dev-gcp
      - application: skjemabygging-experimental
        namespace: skjemadigitalisering
        cluster: dev-gcp
