ingresses:
  - https://skjemabygging-proxy.intern.nav.no
  - https://skjemabygging-proxy.prod-fss-pub.nais.io
env:
  - name: NORG2_BASE_URL
    value: https://norg2.nais.adeo.no
azure:
  application:
    tenant: nav.no
accessPolicy:
  inbound:
    rules:
      - application: skjemautfylling
        namespace: skjemadigitalisering
        cluster: prod-gcp
