name: Build and deploy
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Build tag and push Docker image
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: skjemadigitalisering
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: prod
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-prod:
    name: Deploy prod-fss
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/nais.yaml
          VARS: .nais/prod-vars.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
