name: Skjemabygging-proxy alerts
on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts.yaml'
      - '.nais/dev-vars.yaml'
      - '.nais/prod-vars.yaml'
      - '.github/workflows/deploy-alerts.yaml'

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/alerts.yaml
          VARS: .nais/dev-vars.yaml

      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/alerts.yaml
          VARS: .nais/prod-vars.yaml